# version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    image: avi03/frontimage1:v1
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    image: avi03/backendimage1:v1
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env